### ISSUE TITLE
Query functions ordered by distance

### ISSUE THREAD

**Issue by 8bitskull** [selimanac/DAABBCC#5]
Would love to have either separate functions or a function option that returns hits ordered by distance.

Use case for example would be a unit seeking to target an enemy. It gets a list of enemies within its range using daabbcc.query(), and saves the first instance as a target because the table is ordered by distance.

**Comment by selimanac** [comment]
actually, I guess did this for my old project. I was searching for nearest enemy(or hero) in attack range on turn based game. It was a draft quality project but I'm going to try to find the code that I did. It might be useful.

**Comment by paweljarosz** [comment]
I believe the only struggle here would be to extract the positions for given ids from the dynamic tree to calculate those distances, right? ;)

**Comment by selimanac** [comment]
> I believe the only struggle here would be to extract the positions for given ids from the dynamic tree to calculate those distances, right? ;)

Nope, this is the easiest part. It is possible to extract their center position and distance from given id. I already have those math functions. Most challenging part is the ordering the array by distance with ids. :) Unfortunately it is not simple as lua with C.

**Comment by selimanac** [comment]
Hi @8bitskull

Distance based shorting is on dev branch now. Please use this url as dependency: 
https://github.com/selimanac/DAABBCC/archive/refs/heads/dev.zip

I'm going to clean up the code if works for you. I just did a few small sized tests but it is hard for me to test it on large scales as your game require. 

I prefer to use separate functions since I don't want to implement an extra if-else check on the exist functions. Params are same. It is enough to add `"_short" `at the end:
- `aabb.query_id_short(group_id, aabb_id)`
- `aabb.query_short(group_id, x, y, w, h)`
- `aabb.raycast_short(group_id, start_x, start_y, end_x, end_y)`

I made a change on returning results. Now, they are returning IDs and Distances. This might cause you a lot of extra work. 
If so, please let me know, I can remove the distance from results and just kept the ID as before. But it might be useful(double checking) to compering the distances between those results and your Lua results:
```Lua
{ --[[0x10e32b530]]
  1 = { --[[0x10e32b590]]
    id = 3,
    distance = 0
  },
  2 = { --[[0x10e32b630]]
    id = 0,
    distance = 39
  }
}
```

Also I updated the [example](https://github.com/selimanac/DAABBCC/blob/dev/main/test/test.script)(it is the same but just in case)

I hope this cause a performance gain...
I don't have high hopes but I'm going to take a look at the other issue today.

**Comment by 8bitskull** [comment]
Thanks very much @selimanac.

I can confirm that it works as expected. It reduces my targeting function from 24 lines to 9 lines and produces much more robust results - before, my function was guessing the closest enemy within an error margin to save on performance. Now I get the actual closest enemy.

**Comment by selimanac** [comment]
@8bitskull I made a typo on function names. All `"_short" ` -> `"_sort ` now. Sorry about that. 
You can check out the 2.1 branch(default branch now).  Also updated the readme.
I'm going to close this issue now, feel free to open a new issue if there is a problem.
